### ISSUE TITLE
add     "GASPRIORITY_FOR_ETH_ONLY": "1.5"  to the default tokens.json

### ISSUE THREAD

**Issue by tsarbuig** [yaqub0r/LimitSwap#12]
I forgot to do it too

    "GASPRIORITY_FOR_ETH_ONLY": "1.5"

**Comment by yaqub0r** [comment]
default_value_settings = {
        'SLIPPAGE' : 49,
        'MAXTOKENS' : 0,
        'MOONBAG' : 0,
        'SELLAMOUNTINTOKENS' : 'all',
        'GAS' : 8,
        'BOOSTPERCENT' : 50,
        'GASLIMIT' : 1000000,
        'BUYAFTER_XXX_SECONDS' : 0,
        'MAX_FAILED_TRANSACTIONS_IN_A_ROW' : 2,
        'GASPRIORITY_FOR_ETH_ONLY' : 1.5,
        'STOPLOSSPRICEINBASE' : 0
    }
