### ISSUE TITLE
improve "Found liquidity for CAKE"

### ISSUE THREAD

**Issue by tsarbuig** [yaqub0r/LimitSwap#13]
please add the amount of Liquidity found, something like : 

Found liquidity for CAKE : 1000 BNB

**Comment by yaqub0r** [comment]
I'm not sure what you mean, we already do this:

                                if token["LIQUIDITYCHECK"] == 'true' and token['_LIQUIDITY_CHECKED'] == False:
                                    pool = check_pool(inToken, outToken, token['BASESYMBOL'])
                                    printt("You have set LIQUIDITYCHECK = true.")
                                    printt("Current", token['SYMBOL'], "Liquidity =", int(pool), "in token:",outToken)

                                    if float(token['LIQUIDITYAMOUNT']) <= float(pool):
                                        printt_ok("LIQUIDITYAMOUNT parameter =", int(token['LIQUIDITYAMOUNT']),
                                                    " --> Enough liquidity detected : Buy Signal Found!")
                                    
                                    # This position isn't looking good. Inform the user, disable the token and break out of this loop
                                    else:
                                        printt_warn("LIQUIDITYAMOUNT parameter =", int(token['LIQUIDITYAMOUNT']),
                                                " : not enough liquidity, bot will not buy. Disableing the trade of this token.")
                                        token['ENABLED'] = 'false'
                                        quote = 0
                                        break
