### ISSUE TITLE
mistake in my PREAPPROVE symbol

### ISSUE THREAD

**Issue by tsarbuig** [yaqub0r/LimitSwap#16]
I made a mistake in my preapprove, it's "BASESYMBOL" instead of "SYMBOL" here : 

(2 lines before the end)

```
def preapprove(tokens):
    # We ask the bot to check if your allowance is > to your balance. Use a 10000000000000000 multiplier for decimals.

    # First in all the tokens of the tokens.json
    for token in tokens:

        balance = Web3.fromWei(check_balance(token['ADDRESS'], token['SYMBOL']), 'ether')
        check_approval(token, token['ADDRESS'], balance * 10000000000000000)

        # then of the base pair
        if token['USECUSTOMBASEPAIR'].lower() == 'false':
            balanceweth = Web3.fromWei(client.eth.getBalance(settings['WALLETADDRESS']), 'ether')
            check_approval(token, weth, balanceweth * 10000000000000000)
        else:
            balancebase = Web3.fromWei(check_balance(token['BASEADDRESS'], token['BASESYMBOL']), 'ether')
            check_approval(token, token['BASEADDRESS'], balancebase * 10000000000000000)
```

**Comment by yaqub0r** [comment]
Fixed:

def preapprove(tokens):
    # We ask the bot to check if your allowance is > to your balance. Use a 10000000000000000 multiplier for decimals.

    # First in all the tokens of the tokens.json
    printt_debug("ENTER - preapprove()")

    for token in tokens:

        balance = Web3.fromWei(check_balance(token['ADDRESS'], token['SYMBOL']), 'ether')
        printt_debug("Balance:", balance)
        check_approval(token, token['ADDRESS'], balance * 10000000000000000)
       
        # then of the base pair
        if token['USECUSTOMBASEPAIR'].lower() == 'false':
            balanceweth = Web3.fromWei(client.eth.getBalance(settings['WALLETADDRESS']), 'ether')
            printt_debug("Balanceweth:", balanceweth)
            check_approval(token, weth, balanceweth * 10000000000000000)
        else:
            balancebase = Web3.fromWei(check_balance(token['BASEADDRESS'], token['BASESYMBOL']), 'ether')
            printt_debug("Balancebase:", balancebase)
            check_approval(token, token['BASEADDRESS'], balancebase * 10000000000000000)

    printt_debug("EXIT - preapprove()")
